name: test

on:
  push:
  pull_request:

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -v -race -coverprofile=coverage.out ./...
